version: '3'
services:
    pokemon-api:
        build: ./Cryptocop.Software.Api
        container_name: Cryptocop.Software.Api
        ports:
            - "5000"
        networks:
            - "cryptocop-network"
    cryptocop-payments:
        build: ./cryptocop-payments
        container_name: cryptocop-payments
        networks:
            - "cryptocop-network"
    cryptocop-emails:
      build: ./cryptocop-emails
      container_name: cryptocop-emails
      networks:
          - "cryptocop-network"
    cryptocop-db:
        image: postgres
        container_name: cryptocop-db
        networks:
            - "cryptocop-network"
networks:
    cryptocop-network:
        driver: bridge